import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";

import "primevue/resources/primevue.min.css";
import "primevue/resources/themes/saga-blue/theme.css";

import PrimeVue from "primevue/config";
import AutoComplete from "primevue/autocomplete";
import Accordion from "primevue/accordion";
import AccordionTab from "primevue/accordiontab";
import Avatar from "primevue/avatar";
import AvatarGroup from "primevue/avatargroup";
import Badge from "primevue/badge";
import BadgeDirective from "primevue/badgedirective";
import Button from "primevue/button";
import Breadcrumb from "primevue/breadcrumb";
import Calendar from "primevue/calendar";
import Card from "primevue/card";
import Carousel from "primevue/carousel";
import Chart from "primevue/chart";
import Checkbox from "primevue/checkbox";
import Chip from "primevue/chip";
import Chips from "primevue/chips";
import ColorPicker from "primevue/colorpicker";
import Column from "primevue/column";
import ConfirmDialog from "primevue/confirmdialog";
import ConfirmPopup from "primevue/confirmpopup";
import ConfirmationService from "primevue/confirmationservice";
import ContextMenu from "primevue/contextmenu";
import DataTable from "primevue/datatable";
import DataView from "primevue/dataview";
import DataViewLayoutOptions from "primevue/dataviewlayoutoptions";
import Dialog from "primevue/dialog";
import Divider from "primevue/divider";
import Dropdown from "primevue/dropdown";
import Fieldset from "primevue/fieldset";
import FileUpload from "primevue/fileupload";
import InlineMessage from "primevue/inlinemessage";
import Inplace from "primevue/inplace";
import InputMask from "primevue/inputmask";
import InputNumber from "primevue/inputnumber";
import InputSwitch from "primevue/inputswitch";
import InputText from "primevue/inputtext";
import Knob from "primevue/knob";
import Galleria from "primevue/galleria";
import Listbox from "primevue/listbox";
import MegaMenu from "primevue/megamenu";
import Menu from "primevue/menu";
import Menubar from "primevue/menubar";
import Message from "primevue/message";
import MultiSelect from "primevue/multiselect";
import OrderList from "primevue/orderlist";
import OrganizationChart from "primevue/organizationchart";
import OverlayPanel from "primevue/overlaypanel";
import Paginator from "primevue/paginator";
import Panel from "primevue/panel";
import PanelMenu from "primevue/panelmenu";
import Password from "primevue/password";
import PickList from "primevue/picklist";
import ProgressBar from "primevue/progressbar";
import Rating from "primevue/rating";
import RadioButton from "primevue/radiobutton";
import Ripple from "primevue/ripple";
import SelectButton from "primevue/selectbutton";
import ScrollPanel from "primevue/scrollpanel";
import ScrollTop from "primevue/scrolltop";
import Slider from "primevue/slider";
import Sidebar from "primevue/sidebar";
import Skeleton from "primevue/skeleton";
import SplitButton from "primevue/splitbutton";
import Splitter from "primevue/splitter";
import SplitterPanel from "primevue/splitterpanel";
import Steps from "primevue/steps";
import StyleClass from "primevue/styleclass";
import TabMenu from "primevue/tabmenu";
import Tag from "primevue/tag";
import TieredMenu from "primevue/tieredmenu";
import Textarea from "primevue/textarea";
import Timeline from "primevue/timeline";
import Toast from "primevue/toast";
import ToastService from "primevue/toastservice";
import Toolbar from "primevue/toolbar";
import TabView from "primevue/tabview";
import TabPanel from "primevue/tabpanel";
import Tooltip from "primevue/tooltip";
import ToggleButton from "primevue/togglebutton";
import Tree from "primevue/tree";
import TreeTable from "primevue/treetable";
import TriStateCheckbox from "primevue/tristatecheckbox";

const app = createApp(App);

app.use(PrimeVue, { ripple: true, inputStyle: "outlined" });
app.use(router);
app.use(PrimeVue);
app.use(ConfirmationService);
app.use(ToastService);

app.directive("tooltip", Tooltip);
app.directive("ripple", Ripple);
app.directive("badge", BadgeDirective);
app.directive("styleclass", StyleClass);

app.component("Primevue-Accordion", Accordion);
app.component("Primevue-AccordionTab", AccordionTab);
app.component("Primevue-AutoComplete", AutoComplete);
app.component("Primevue-Avatar", Avatar);
app.component("Primevue-AvatarGroup", AvatarGroup);
app.component("Primevue-Badge", Badge);
app.component("Primevue-Breadcrumb", Breadcrumb);
app.component("Primevue-Button", Button);
app.component("Primevue-Calendar", Calendar);
app.component("Primevue-Card", Card);
app.component("Primevue-Carousel", Carousel);
app.component("Primevue-Chart", Chart);
app.component("Primevue-Checkbox", Checkbox);
app.component("Primevue-Chip", Chip);
app.component("Primevue-Chips", Chips);
app.component("Primevue-ColorPicker", ColorPicker);
app.component("Primevue-Column", Column);
app.component("Primevue-ConfirmDialog", ConfirmDialog);
app.component("Primevue-ConfirmPopup", ConfirmPopup);
app.component("Primevue-ContextMenu", ContextMenu);
app.component("Primevue-DataTable", DataTable);
app.component("Primevue-DataView", DataView);
app.component("Primevue-DataViewLayoutOptions", DataViewLayoutOptions);
app.component("Primevue-Dialog", Dialog);
app.component("Primevue-Divider", Divider);
app.component("Primevue-Dropdown", Dropdown);
app.component("Primevue-Fieldset", Fieldset);
app.component("Primevue-FileUpload", FileUpload);
app.component("Primevue-InlineMessage", InlineMessage);
app.component("Primevue-Inplace", Inplace);
app.component("Primevue-InputMask", InputMask);
app.component("Primevue-InputNumber", InputNumber);
app.component("Primevue-InputSwitch", InputSwitch);
app.component("Primevue-InputText", InputText);
app.component("Primevue-Galleria", Galleria);
app.component("Primevue-Knob", Knob);
app.component("Primevue-Listbox", Listbox);
app.component("Primevue-MegaMenu", MegaMenu);
app.component("Primevue-Menu", Menu);
app.component("Primevue-Menubar", Menubar);
app.component("Primevue-Message", Message);
app.component("Primevue-MultiSelect", MultiSelect);
app.component("Primevue-OrderList", OrderList);
app.component("Primevue-OrganizationChart", OrganizationChart);
app.component("Primevue-OverlayPanel", OverlayPanel);
app.component("Primevue-Paginator", Paginator);
app.component("Primevue-Panel", Panel);
app.component("Primevue-PanelMenu", PanelMenu);
app.component("Primevue-Password", Password);
app.component("Primevue-PickList", PickList);
app.component("Primevue-ProgressBar", ProgressBar);
app.component("Primevue-RadioButton", RadioButton);
app.component("Primevue-Rating", Rating);
app.component("Primevue-SelectButton", SelectButton);
app.component("Primevue-ScrollPanel", ScrollPanel);
app.component("Primevue-ScrollTop", ScrollTop);
app.component("Primevue-Slider", Slider);
app.component("Primevue-Sidebar", Sidebar);
app.component("Primevue-Skeleton", Skeleton);
app.component("Primevue-SplitButton", SplitButton);
app.component("Primevue-Splitter", Splitter);
app.component("Primevue-SplitterPanel", SplitterPanel);
app.component("Primevue-Steps", Steps);
app.component("Primevue-TabMenu", TabMenu);
app.component("Primevue-TabView", TabView);
app.component("Primevue-TabPanel", TabPanel);
app.component("Primevue-Tag", Tag);
app.component("Primevue-Textarea", Textarea);
app.component("Primevue-TieredMenu", TieredMenu);
app.component("Primevue-Timeline", Timeline);
app.component("Primevue-Toast", Toast);
app.component("Primevue-Toolbar", Toolbar);
app.component("Primevue-ToggleButton", ToggleButton);
app.component("Primevue-Tree", Tree);
app.component("Primevue-TreeTable", TreeTable);
app.component("Primevue-TriStateCheckbox", TriStateCheckbox);

app.mount("#app");
